/**
 * Documentary photography registry — Turkish industrial atmosphere.
 * Stock-sourced editorial placeholders; live campaigns use company photos.
 */
export const media = {
  /** Hero — late-afternoon factory floor */
  factoryFloor: {
    src: "/media/factory-floor.jpg",
    altTr: "Fabrika üretim alanı, geç öğleden sonra ışığı",
    altEn: "Factory production floor, late afternoon light",
    credit: "Unsplash",
    focalPoint: "center 45%",
    aspect: "panorama" as const,
    mood: "cinematic",
  },
  cncWorkshop: {
    src: "/media/cnc-workshop.jpg",
    altTr: "CNC işleme atölyesi",
    altEn: "CNC machining workshop",
    credit: "Unsplash",
    focalPoint: "center 40%",
    aspect: "editorial" as const,
    mood: "operational",
  },
  logisticsDock: {
    src: "/media/logistics-dock.jpg",
    altTr: "Lojistik yükleme alanı",
    altEn: "Logistics loading dock",
    credit: "Unsplash",
    focalPoint: "center 55%",
    aspect: "panorama" as const,
    mood: "export",
  },
  exportWarehouse: {
    src: "/media/export-warehouse.jpg",
    altTr: "İhracat deposu ve sevkiyat",
    altEn: "Export warehouse and dispatch",
    credit: "Unsplash",
    focalPoint: "center 50%",
    aspect: "panorama" as const,
    mood: "movement",
  },
  machineOperator: {
    src: "/media/machine-operator.jpg",
    altTr: "Tezgâh operatörü, üretim hattı",
    altEn: "Machine operator on production line",
    credit: "Unsplash",
    focalPoint: "center 42%",
    aspect: "editorial" as const,
    mood: "human",
  },
  packagingFloor: {
    src: "/media/packaging-floor.jpg",
    altTr: "Ambalaj ve sevkiyat katı",
    altEn: "Packaging and dispatch floor",
    credit: "Unsplash",
    focalPoint: "center 48%",
    aspect: "panorama" as const,
    mood: "grounded",
  },
  factoryDetail: {
    src: "/media/factory-detail.jpg",
    altTr: "Endüstriyel makine detayı",
    altEn: "Industrial machinery detail",
    credit: "Unsplash",
    focalPoint: "center 50%",
    aspect: "editorial" as const,
    mood: "texture",
  },
  textileFloor: {
    src: "/media/textile-floor.jpg",
    altTr: "Tekstil üretim hattı",
    altEn: "Textile production line",
    credit: "Unsplash",
    focalPoint: "center 50%",
    aspect: "editorial" as const,
    mood: "warm",
  },
  industrialLine: {
    src: "/media/industrial-line.jpg",
    altTr: "Endüstriyel üretim hattı",
    altEn: "Industrial production line",
    credit: "Unsplash",
    focalPoint: "center 42%",
    aspect: "editorial" as const,
    mood: "operational",
  },
  warehouse: {
    src: "/media/warehouse.jpg",
    altTr: "Depo ve lojistik alanı",
    altEn: "Warehouse and logistics area",
    credit: "Unsplash",
    focalPoint: "center 55%",
    aspect: "panorama" as const,
    mood: "grounded",
  },
  workshop: {
    src: "/media/workshop.jpg",
    altTr: "Atölye ve üretim alanı",
    altEn: "Workshop and production floor",
    credit: "Unsplash",
    focalPoint: "center 40%",
    aspect: "panorama" as const,
    mood: "human",
  },
  agrifoodColdchain: {
    src: "/media/agrifood-coldchain.jpg",
    altTr: "Tarım işleme ve soğuk zincir tesisi",
    altEn: "Agricultural processing and cold chain facility",
    credit: "Unsplash",
    focalPoint: "center 45%",
    aspect: "editorial" as const,
    mood: "operational",
  },
  grainMill: {
    src: "/media/grain-mill.jpg",
    altTr: "Un ve tahıl değirmen tesisi",
    altEn: "Grain and flour mill facility",
    credit: "Unsplash",
    focalPoint: "center 50%",
    aspect: "editorial" as const,
    mood: "grounded",
  },
  greenhouse: {
    src: "/media/greenhouse.jpg",
    altTr: "Seracılık ve iklim kontrollü üretim",
    altEn: "Greenhouse and climate-controlled cultivation",
    credit: "Unsplash",
    focalPoint: "center 42%",
    aspect: "panorama" as const,
    mood: "operational",
  },
  chemicalPlant: {
    src: "/media/chemical-plant.jpg",
    altTr: "Kimya ve proses tesis interior",
    altEn: "Chemical and process plant interior",
    credit: "Unsplash",
    focalPoint: "center 48%",
    aspect: "editorial" as const,
    mood: "texture",
  },
  ceramicKiln: {
    src: "/media/ceramic-kiln.jpg",
    altTr: "Seramik ve refrakter üretim hattı",
    altEn: "Ceramic and refractory production line",
    credit: "Unsplash",
    focalPoint: "center 44%",
    aspect: "editorial" as const,
    mood: "warm",
  },
  foodProcessing: {
    src: "/media/food-processing.jpg",
    altTr: "Gıda işleme ve paketleme hattı",
    altEn: "Food processing and packaging line",
    credit: "Unsplash",
    focalPoint: "center 46%",
    aspect: "panorama" as const,
    mood: "grounded",
  },
  shipyardDock: {
    src: "/media/shipyard-dock.jpg",
    altTr: "Gemi ekipmanı ve denizcilik sanayi",
    altEn: "Marine equipment and shipbuilding industry",
    credit: "Unsplash",
    focalPoint: "center 52%",
    aspect: "panorama" as const,
    mood: "export",
  },
  glassFurnace: {
    src: "/media/glass-furnace.jpg",
    altTr: "Cam ve endüstriyel fırın tesisi",
    altEn: "Glass and industrial furnace facility",
    credit: "Unsplash",
    focalPoint: "center 50%",
    aspect: "editorial" as const,
    mood: "cinematic",
  },
  spinningMill: {
    src: "/media/spinning-mill.jpg",
    altTr: "İplik ve dokuma üretim hattı",
    altEn: "Yarn and weaving production line",
    credit: "Unsplash",
    focalPoint: "center 48%",
    aspect: "editorial" as const,
    mood: "operational",
  },
  plasticExtrusion: {
    src: "/media/plastic-extrusion.jpg",
    altTr: "Plastik ambalaj ve ekstrüzyon hattı",
    altEn: "Plastic packaging and extrusion line",
    credit: "Unsplash",
    focalPoint: "center 45%",
    aspect: "editorial" as const,
    mood: "operational",
  },
} as const;

export type MediaKey = keyof typeof media;
