import { buildCatalogCampaign } from "../build-campaign";

export const anadoluCam = buildCatalogCampaign({
  slug: "anadolu-cam-kayseri", legalName: "Anadolu Cam İşleme ve Yapı Sistemleri A.Ş.", tradeName: "Anadolu Cam İşleme", sector: "Lamine cam ve yapı cephe cam işleme", city: "Kayseri", region: "1. Organize Sanayi Bölgesi", founded: 2005, employees: 52, exportMarkets: ["Irak", "Azerbaycan", "Türkmenistan"], facilityArea: "4.600 m² kesim ve lamine", monthlyCapacity: "Aylık ~28.000 m² cam işleme", targetTry: 8_200_000, exportShare: "Gelirin ~%44'i", domesticShare: "~%56", reviewStatus: "document_review", processDone: 2, fundingPurpose: "Otomatik lamine hattı ve büyük format kesim masası : AVM cephe projelerinde lead time 10 haftadan 6 haftaya.", fundingLines: [
    { label: "Lamine otoclave hattı", amountTry: 3_400_000, percent: 41 }, { label: "CNC cam kesim (jumbo format)", amountTry: 2_100_000, percent: 26 }, { label: "Silikon ve fitil stoku", amountTry: 900_000, percent: 11 }, { label: "Proje lojistik rampası", amountTry: 1_000_000, percent: 12 }, { label: "İşletme sermayesi", amountTry: 800_000, percent: 10 }, ], founderName: "Fatih Anadolu", founderNote: "Kayseri inşaat projeleri ve Orta Asya ihracatı. Büyük proje yoğunlaşması riski var , lamine hat şart.", storyOrigin: "2005'te cam kesim atölyesi. 2012'de lamine lisansı ve ilk AVM cephe projesi.", storyToday: "Düz cam, lamine, temper. Irak inşaat projeleri ve Azerbaycan cephe sistemleri.", productionDetail: "Cam kabul → kesim → kenar işleme → lamine (otoclave) → temper (dış kaynak) → paketleme.", processes: ["Kesim", "Kenar işleme", "Lamine", "Kalite kontrol", "Paketleme"], materials: ["Float cam", "PVB film", "Silikon"], machines: [
    { id: "cut", name: "Lisec jumbo kesim · 2014", role: "Kesim", year: 2014, note: "3,2 m limit : büyük proje darboğaz." }, { id: "lam", name: "Yarı otomatik lamine", role: "Lamine", year: 2012, note: "Manuel PVB : otoclave yatırım hedefi." }, ], risks: [
    { title: "Proje yoğunlaşması", text: "Gelirin %35'i tek Irak AVM projesine bağlı : gecikme cezası yüksek." }, { title: "Cam kırılma lojistik", text: "Uzun mesafe sevkiyatta kırılma oranı %1,8 : sigorta primi arttı." }, ], gateway: {
    hook: "Kayseri'de lamine cam : büyük proje lead time 10 hafta, otoclave yatırımı gerekli.", scale: "52 çalışan · 28.000 m²/ay · Orta Asya ihracat", tension: "Tek büyük Irak projesi gelirin üçte birini taşıyor : lamine kapasitesi geciktiriyor.", }, bottleneck: { label: "Lamine kapasitesi", note: "Manuel PVB yerleştirme : büyük formatta 10 hafta lead time." }, journal: [
    { date: "2026-05-15", time: "13:45", text: "Lamine hattında Irak projesi paneli : PVB hava kabarcığı tespit edildi, panel hurda.", type: "inspection" }, { date: "2026-05-15", time: "15:10", text: "Kesim masasında jumbo limit nedeniyle panel ikiye bölündü : müşteri onayı bekleniyor.", type: "capacity" }, { date: "2026-05-07", time: "10:20", text: "İhracat sevkiyat planı: Azerbaycan 2 TIR, Türkmenistan 1 TIR : tarihler doğrulandı.", type: "logistics" }, { date: "2026-04-30", time: "11:00", text: "Belge incelemesi: 2023-2024 raporları alındı.", type: "inspection" }, { date: "2026-04-18", time: "09:30", text: "Ön başvuru onaylandı : yapı cam sektörü uygun.", type: "observation" }, ], updates: [
    { date: "2026-05-15", time: "16:00", text: "Kapasite ve hurda raporu dosyaya eklendi." }, { date: "2026-05-08", time: "14:30", text: "Sevkiyat planı doğrulandı." }, { date: "2026-05-01", time: "10:45", text: "Finansal raporlar incelemeye alındı." }, { date: "2026-04-19", time: "15:20", text: "Başvuru belgeleri arşivlendi." }, ], timeline: [
    { year: 2005, event: "Cam kesim atölyesi" }, { year: 2012, event: "Lamine lisansı · AVM cephe" }, { year: 2018, event: "Irak inşaat projeleri" }, { year: 2024, event: "Büyük proje yoğunlaşması" }, ], facilityNotes: [
    { zone: "Kesim", note: "Jumbo 3,2 m limit" }, { zone: "Lamine", note: "Manuel PVB" }, { zone: "Sevkiyat", note: "A-frame paket" }, ], exportEvolution: [
    { year: 2014, market: "Irak", note: "İnşaat camı" }, { year: 2019, market: "Azerbaycan", note: "Cephe sistemleri" }, { year: 2022, market: "Türkmenistan", note: "Kamu binaları" }, ], inspectionLayers: [
    { layer: "Belge paketi", status: "partial", note: "Raporlar incelemede" }, { layer: "Proje riski", status: "partial", note: "Irak proje yoğunlaşması not edildi" }, { layer: "Saha", status: "pending", note: "Belge sonrası" }, ], operationalSignals: [
    { label: "Lead time", value: "10 hafta (büyük proje)" }, { label: "Aylık işleme", value: "~28.000 m²" }, { label: "Hurda oranı", value: "%1,4" }, { label: "İhracat payı", value: "Gelirin ~%44'ü" }, ],
});
