import { buildCatalogCampaign } from "../build-campaign";

export const antalyaSera = buildCatalogCampaign({
  slug: "antalya-sera-teknoloji",
  legalName: "Akdeniz Sera Teknolojileri Tarım San. Ltd. Şti.",
  tradeName: "Akdeniz Sera",
  sector: "Seracılık ve tarım teknolojisi · ihracat",
  city: "Antalya",
  region: "Kumluca",
  founded: 2011,
  employees: 48,
  exportMarkets: ["Rusya", "Ukrayna", "Romanya"],
  facilityArea: "12 hektar sera + paketleme",
  monthlyCapacity: "Sezonluk ~850 ton domates (peak)",
  targetTry: 7_800_000,
  exportShare: "Gelirin ~%55'i",
  domesticShare: "~%45",
  reviewStatus: "preliminary_review",
  processDone: 1,
  fundingPurpose: "Iklim kontrollü sera genişletmesi (2 ha), damla sulama otomasyonu ve soğuk zincir paketleme.",
  fundingLines: [
    { label: "Sera genişletme", amountTry: 3_600_000, percent: 46 },
    { label: "Damla sulama IoT", amountTry: 1_400_000, percent: 18 },
    { label: "Soğuk zincir paketleme", amountTry: 1_200_000, percent: 15 },
    { label: "Güneş enerjisi", amountTry: 900_000, percent: 12 },
    { label: "İşletme sermayesi", amountTry: 700_000, percent: 9 },
  ],
  founderName: "Aylin Korkmaz",
  founderNote: "Rusya hattı stabil ama soğuk zincir paketleme eksikliği fire oranını %8'e çıkarıyor.",
  storyOrigin: "2011'de Kumluca'da geleneksel sera. 2018'de iklim kontrollü teknoloji ve ihracat.",
  storyToday: "Domates ve salatalık — Rusya ve Romanya market zincirleri. Antalya tarım koridoru.",
  productionDetail: "Fide → sera yetiştirme → hasat → kalite → soğuk paketleme → sevkiyat.",
  processes: ["Fide", "Sera yetiştirme", "Hasat", "Kalite ayrımı", "Paketleme"],
  materials: ["Fide", "Gübre", "İlaç (kayıtlı)", "Ambalaj"],
  machines: [
    { id: "climate-1", name: "Iklim kontrol ünitesi · 6 ha", role: "Sera", year: 2018, note: "Genişletme hedefi +2 ha." },
    { id: "pack-cold", name: "Ön soğutma odası", role: "Paketleme", year: 2020, note: "Kapasite yetersiz." },
  ],
  risks: [
    { title: "İklim riski", text: "2024 yazında aşırı sıcak 2 ha hasat kaybına yol açtı." },
    { title: "Soğuk zincir", text: "Paketleme kapasitesi ihracat siparişlerini sınırlıyor." },
  ],
  gateway: {
    hook: "Kumluca seracılık — ihracat talebi var, soğuk zincir paketleme darboğazı.",
    scale: "48 çalışan · 12 ha · 3 ihracat pazarı",
    tension: "Hasat peak döneminde paketleme kuyruğu 14 saate çıkıyor.",
  },
  bottleneck: { label: "Soğuk paketleme kapasitesi", note: "Fire oranı %8 — hedef %3." },
  journal: [
    { date: "2026-05-23", time: "05:30", text: "Sabah hasadı: 12 ton domates A sınıfı — paketleme kuyruğu başladı.", type: "capacity" },
    { date: "2026-05-23", time: "08:00", text: "Rusya sevkiyatı için soğuk oda sıcaklık kaydı alındı.", type: "logistics" },
    { date: "2026-05-16", time: "10:15", text: "Sera genişletme arazisi sınır ölçümü tamamlandı.", type: "inspection" },
    { date: "2026-05-09", time: "07:00", text: "Damla sulama sensör kalibrasyonu — 2 hat güncellendi.", type: "observation" },
    { date: "2026-04-30", time: "14:00", text: "Romanya market zinciri denetim ziyareti planlandı.", type: "founder" },
  ],
  updates: [
    { date: "2026-05-23", time: "09:00", text: "Hasat ve soğuk oda kayıtları dosyaya eklendi." },
    { date: "2026-05-16", time: "11:30", text: "Sera genişletme arazi raporu arşivlendi." },
    { date: "2026-05-10", time: "08:00", text: "Sulama IoT teklifleri karşılaştırıldı." },
    { date: "2026-05-01", time: "10:00", text: "Ön eleme belge paketi tamamlandı." },
  ],
  timeline: [
    { year: 2011, event: "Geleneksel sera" },
    { year: 2018, event: "Iklim kontrollü teknoloji" },
    { year: 2021, event: "Rusya market zinciri" },
    { year: 2024, event: "Soğuk zincir darboğazı" },
  ],
  facilityNotes: [
    { zone: "Sera alanı", note: "12 ha" },
    { zone: "Paketleme", note: "Soğuk oda darboğaz" },
    { zone: "Sevkiyat", note: "Antalya havalimanı yakın" },
  ],
  exportEvolution: [
    { year: 2018, market: "Rusya", note: "Domates" },
    { year: 2020, market: "Romanya", note: "Market zinciri" },
    { year: 2022, market: "Ukrayna", note: "Kısmi" },
  ],
  inspectionLayers: [
    { layer: "Belge paketi", status: "partial", note: "Ön eleme" },
    { layer: "Saha doğrulama", status: "pending", note: "Sezon planı" },
    { layer: "Tarım kayıtları", status: "partial", note: "GlobalGAP süreci" },
  ],
  operationalSignals: [
    { label: "Sera alanı", value: "12 ha" },
    { label: "Peak hasat", value: "~850 ton/ay" },
    { label: "İhracat payı", value: "Gelirin ~%55'i" },
    { label: "Fire oranı", value: "~%8" },
  ],
});
