import { buildCatalogCampaign } from "../build-campaign";

export const denizGemiParca = buildCatalogCampaign({
  slug: "deniz-gemi-parca-tuzla", legalName: "Deniz Gemi Ekipmanları Sanayi A.Ş.", tradeName: "Deniz Gemi Ekipmanları", sector: "Gemi donanımı ve denizcilik çelik parça üretimi", city: "İstanbul", region: "Tuzla Tersane Bölgesi", founded: 2007, employees: 44, exportMarkets: ["Norveç", "Yunanistan", "Mısır"], facilityArea: "3.200 m² kaynak ve boya atölyesi", monthlyCapacity: "Aylık ~320 adet denizcilik parça (küçük-orta lot)", targetTry: 6_900_000, exportShare: "Gelirin ~%51'i", domesticShare: "~%49", reviewStatus: "field_verification", processDone: 3, fundingPurpose: "CO2 kaynak hattı kapasite artışı ve kumlama-boya hattı : tersane teslim süresini 8 haftadan 5,5 haftaya indirmek.", fundingLines: [
    { label: "CO2 kaynak ve pozisyonlama", amountTry: 2_800_000, percent: 41 }, { label: "Kumlama ve epoksi boya hattı", amountTry: 1_900_000, percent: 28 }, { label: "NDT test ekipmanı", amountTry: 900_000, percent: 13 }, { label: "Çelik sac stoku", amountTry: 800_000, percent: 12 }, { label: "İşletme sermayesi", amountTry: 500_000, percent: 6 }, ], founderName: "Oğuz Deniz", founderNote: "Tuzla tersanelerine 18 yıldır parça üretiyoruz. Kaynak usta sayısı yetersiz : yeni hat şart.", storyOrigin: "2007'de Tuzla'da gemi tamir atölyesi. 2013'te Norveç tersane alt yüklenicisi.", storyToday: "Paslanmaz ve karbon çelik parça, kaynak, NDT, boya. Tersane siparişleri proje bazlı.", productionDetail: "Sac kesim → şekillendirme → kaynak → NDT → kumlama → epoksi boya → sevkiyat.", processes: ["Sac kesim", "Kaynak", "NDT", "Kumlama", "Epoksi boya"], materials: ["316L paslanmaz", "A36 çelik", "Epoksi boya"], machines: [
    { id: "weld-1", name: "Lincoln CO2 kaynak ×4", role: "Kaynak", year: 2014, note: "2 usta kritik : emeklilik 2027." }, { id: "blast", name: "Kumlama kabini", role: "Yüzey", year: 2011, note: "Dar alan : büyük parçada gecikme." }, ], risks: [
    { title: "Tersane döngüsü", text: "2024'te iki tersane sipariş iptali : nakit akışı etkilendi." }, { title: "Kaynak usta bağımlılığı", text: "Sertifikalı kaynakçı 2 kişi : ikisi 60+ yaş." }, ], gateway: {
    hook: "Tuzla tersane bölgesinde gemi parça : kaynak usta sayısı teslim süresini belirliyor.", scale: "44 çalışan · 4 kaynak pozisyonu · Norveç hat", tension: "8 haftalık teslim : yeni kaynak hattı olmadan tersane sözleşmesi alınamıyor.", }, bottleneck: { label: "Kaynak kapasitesi", note: "4 pozisyon · 2 usta kritik · overtime maliyeti yükseldi." }, journal: [
    { date: "2026-05-22", time: "09:00", text: "Norveç projesi parçasında fillet kaynak görsel muayene : 2 küçük porozite, tamir planlandı.", type: "inspection" }, { date: "2026-05-22", time: "11:30", text: "Kumlama kabininde büyük parça sıra beklemesi: 3 gün.", type: "capacity" }, { date: "2026-05-13", time: "16:00", text: "Tersane referans mektupları 3 müşteriden alındı : 2024 iptal notu dahil.", type: "observation" }, { date: "2026-05-06", time: "10:20", text: "NDT rapor örnekleri incelendi : uyumlu.", type: "inspection" }, { date: "2026-04-28", time: "14:45", text: "Saha ziyareti öncesi kaynak prosedür dosyası gözden geçirildi.", type: "observation" }, ], updates: [
    { date: "2026-05-22", time: "12:00", text: "Saha tutanağı güncellendi." }, { date: "2026-05-14", time: "09:15", text: "Tersane referansları dosyaya eklendi." }, { date: "2026-05-07", time: "16:30", text: "NDT örnek raporları arşivlendi." }, { date: "2026-04-29", time: "11:00", text: "Saha ziyareti randevusu onaylandı." }, ], timeline: [
    { year: 2007, event: "Tuzla tamir atölyesi" }, { year: 2013, event: "Norveç tersane alt yüklenici" }, { year: 2020, event: "Yunanistan küçük proje" }, { year: 2024, event: "İki tersane sipariş iptali" }, ], facilityNotes: [
    { zone: "Kaynak", note: "4 pozisyon · 2 usta kritik" }, { zone: "Kumlama", note: "Dar alan" }, { zone: "Sevkiyat", note: "Tersane vincine yakın" }, ], exportEvolution: [
    { year: 2013, market: "Norveç", note: "Balıkçılık gemisi ekipmanı" }, { year: 2018, market: "Yunanistan", note: "Yat donanımı" }, { year: 2022, market: "Mısır", note: "Tersane tamir" }, ], inspectionLayers: [
    { layer: "Belge paketi", status: "partial", note: "NDT raporları tamam" }, { layer: "Saha doğrulama", status: "partial", note: "Kaynak gözlemi yapıldı" }, { layer: "Müşteri referans", status: "partial", note: "3 tersane mektubu" }, ], operationalSignals: [
    { label: "Teslim süresi", value: "8 hafta ort." }, { label: "Kaynak usta", value: "2 kritik" }, { label: "Aylık parça", value: "~320 adet" }, { label: "İhracat payı", value: "Gelirin ~%51'i" }, ],
});
