import { buildCatalogCampaign } from "../build-campaign";

export const eskisehirSeramik = buildCatalogCampaign({
  slug: "eskisehir-seramik",
  legalName: "Eskişehir Endüstriyel Seramik Sanayi Ltd. Şti.",
  tradeName: "Eskişehir Seramik",
  sector: "Endüstriyel seramik ve refrakter üretimi",
  city: "Eskişehir",
  region: "Eskişehir 1. OSB",
  founded: 2004,
  employees: 63,
  exportMarkets: ["Almanya", "Romanya", "Ukrayna (askıda kısmi)"],
  facilityArea: "5.400 m² fırın ve şekillendirme",
  monthlyCapacity: "Aylık ~180 ton seramik parça",
  targetTry: 9_600_000,
  exportShare: "Gelirin ~%48'i",
  domesticShare: "~%52",
  reviewStatus: "field_verification",
  processDone: 3,
  fundingPurpose: "Tunnel fırın enerji verimliliği (recuperator), CNC şekillendirme tezgâhı ve kalite laboratuvarı genişletmesi.",
  fundingLines: [
    { label: "Fırın recuperator", amountTry: 3_400_000, percent: 35 },
    { label: "CNC şekillendirme", amountTry: 2_500_000, percent: 26 },
    { label: "Kalite laboratuvarı", amountTry: 1_200_000, percent: 13 },
    { label: "Hammadde silosu", amountTry: 1_400_000, percent: 15 },
    { label: "İşletme sermayesi", amountTry: 1_100_000, percent: 11 },
  ],
  founderName: "Selim Eren",
  founderNote: "Enerji maliyeti 2024'te cironun %19'una çıktı — recuperator yatırımı zorunlu.",
  storyOrigin: "2004'te refrakter tuğla üretimi. 2014'te endüstriyel seramik parça ihracatına geçiş.",
  storyToday: "Çimento ve çelik fabrikalarına refrakter; Almanya OEM parça ihracatı. Eskişehir-Ankara sanayi koridoru.",
  productionDetail: "Hammadde karışım → pres → kurutma → fırın → kalite → paketleme.",
  processes: ["Karışım", "Presleme", "Kurutma", "Tunnel fırın", "Kalite kontrol"],
  materials: ["Kaolin", "Alümina", "Boksit"],
  machines: [
    { id: "kiln-1", name: "Tunnel fırın · 85m", role: "Pişirme", year: 2009, note: "Recuperator yok — yüksek gaz tüketimi." },
    { id: "press-1", name: "Hidrolik pres · 800 ton", role: "Şekillendirme", year: 2011, note: "Kalıp değişim süresi uzun." },
  ],
  risks: [
    { title: "Enerji maliyeti", text: "Doğalgaz fiyatı 2023–2024'te %40 arttı; fırın verimsizliği marjı eritiyor." },
    { title: "Ukrayna pazarı", text: "2022 sonrası hacim düştü; Almanya ile denge aranıyor." },
  ],
  gateway: {
    hook: "Eskişehir OSB'de refrakter seramik — fırın enerji verimsizliği ihracat marjını tehdit ediyor.",
    scale: "63 çalışan · 180 ton/ay · 3 ihracat pazarı",
    tension: "Recuperator olmadan birim enerji maliyeti sektör ortalamasının %22 üzerinde.",
  },
  bottleneck: { label: "Fırın enerji verimsizliği", note: "Son fatura döneminde gaz gideri %31 arttı." },
  journal: [
    { date: "2026-05-21", time: "06:30", text: "Tunnel fırın sıcaklık profili kaydedildi — recuperator öncesi baz ölçüm.", type: "capacity" },
    { date: "2026-05-21", time: "11:00", text: "Almanya OEM parti kalite testi geçti — sevkiyat onaylandı.", type: "logistics" },
    { date: "2026-05-13", time: "09:45", text: "Pres kalıp seti değişimi gözlemlendi — 47 dk duruş.", type: "observation" },
    { date: "2026-05-06", time: "14:20", text: "Recuperator teklifleri dosyaya eklendi — 3 tedarikçi.", type: "inspection" },
    { date: "2026-04-24", time: "10:00", text: "Romanya distribütör sipariş artışı — kapasite %88.", type: "founder" },
  ],
  updates: [
    { date: "2026-05-21", time: "12:00", text: "Fırın enerji baz ölçümü arşivlendi." },
    { date: "2026-05-13", time: "15:00", text: "Almanya sevkiyat kalite sertifikası eklendi." },
    { date: "2026-05-07", time: "09:30", text: "Recuperator teklif karşılaştırması dosyalandı." },
    { date: "2026-04-25", time: "16:00", text: "Saha ziyareti fotoğrafları yüklendi." },
  ],
  timeline: [
    { year: 2004, event: "Refrakter tuğla" },
    { year: 2014, event: "Endüstriyel seramik ihracat" },
    { year: 2019, event: "Almanya OEM anlaşması" },
    { year: 2024, event: "Enerji maliyeti krizi" },
  ],
  facilityNotes: [
    { zone: "Fırın hattı", note: "Tunnel 85m" },
    { zone: "Pres atölyesi", note: "2 hidrolik pres" },
    { zone: "Laboratuvar", note: "Genişletme planlı" },
  ],
  exportEvolution: [
    { year: 2014, market: "Romanya", note: "Refrakter" },
    { year: 2018, market: "Almanya", note: "OEM parça" },
    { year: 2020, market: "Ukrayna", note: "Kısmi askı" },
  ],
  inspectionLayers: [
    { layer: "Belge paketi", status: "done", note: "Tamam" },
    { layer: "Saha doğrulama", status: "partial", note: "Fırın ziyareti yapıldı" },
    { layer: "Enerji denetimi", status: "partial", note: "Baz ölçüm kayıtlı" },
  ],
  operationalSignals: [
    { label: "Aylık seramik", value: "~180 ton" },
    { label: "Enerji/ciro", value: "~%19" },
    { label: "İhracat payı", value: "Gelirin ~%48'i" },
    { label: "Son saha", value: "21 Mayıs 2026" },
  ],
});
