import { buildCatalogCampaign } from "../build-campaign";

export const marmaraKimya = buildCatalogCampaign({
  slug: "marmara-kimya-kocaeli", legalName: "Marmara Endüstriyel Kimya Sanayi A.Ş.", tradeName: "Marmara Kimya", sector: "Endüstriyel reçine ve proses kimya üretimi", city: "Kocaeli", region: "Gebze OSB", founded: 2006, employees: 71, exportMarkets: ["Irak", "Gürcistan", "Bulgaristan"], facilityArea: "6.200 m² reaktör ve depolama", monthlyCapacity: "Aylık ~420 ton reçine proses kapasitesi", targetTry: 11_200_000, exportShare: "Gelirin ~%35'i", domesticShare: "~%65", reviewStatus: "field_verification", processDone: 3, fundingPurpose: "Reaktör hattı modernizasyonu (DCS entegrasyonu) ve atık geri kazanım ünitesi kapasite artışı.", fundingLines: [
    { label: "Reaktör DCS ve otomasyon", amountTry: 4_100_000, percent: 37 }, { label: "Atık geri kazanım ünitesi", amountTry: 2_600_000, percent: 23 }, { label: "Emniyet enstrümantasyonu", amountTry: 1_500_000, percent: 13 }, { label: "Hammadde tank çiftliği", amountTry: 1_800_000, percent: 16 }, { label: "İşletme sermayesi", amountTry: 1_200_000, percent: 11 }, ], founderName: "Ayşe Marmara", founderNote: "Proses güvenliği önceliğimiz. 2024 ÇED kapasite uyarısı var : yatırım planı bunu kapatıyor.", storyOrigin: "2006'da Gebze'de epoksi reçine fason üretim. 2012'de kendi markalı endüstriyel reçine.", storyToday: "Otomotiv ve inşaat sektörüne reçine tedarik. İhracat Irak ve Gürcistan ağırlıklı; iç pazar Kocaeli sanayi.", productionDetail: "Monomer alımı → reaktör (batch) → soğutma → filtreleme → dolum → depolama.", processes: ["Monomer alım", "Batch reaktör", "Soğutma", "Filtrasyon", "Dolum"], materials: ["Epoksi monomer", "Sertleştirici", "Katalizör"], machines: [
    { id: "rx-1", name: "Paslanmaz batch reaktör · 12 m³", role: "Reaktör", year: 2008, note: "Manuel kontrol : DCS yatırım hedefi." }, { id: "recovery", name: "Solvent geri kazanım ünitesi", role: "Atık", year: 2015, note: "Kapasite sınırda · genişleme planlı." }, ], risks: [
    { title: "ÇED kapasite uyarısı", text: "2024 denetimde atıksu kapasite artışı şartı kondu. Yatırım yapılmazsa üretim kısıtı riski." }, { title: "Hammadde fiyatı", text: "Epoksi monomer LME+navlun etkisiyle 2024'te %31 arttı." }, ], gateway: {
    hook: "Gebze OSB'de endüstriyel reçine : ÇED uyarısı kapasite artırımını zorunlu kılıyor.", scale: "71 çalışan · 12 m³ reaktör · 3 ihracat pazarı", tension: "Manuel reaktör kontrolü : DCS olmadan batch tutarlılığı operatöre bağlı.", }, bottleneck: { label: "Reaktör DCS eksikliği", note: "Batch sıcaklık sapması son 6 ayda 4 kez tolerans dışı." }, journal: [
    { date: "2026-05-20", time: "08:50", text: "Reaktör odasında PPE ve acil duş protokolü doğrulandı. Ex-proof aydınlatma tamam.", type: "inspection" }, { date: "2026-05-20", time: "10:10", text: "Son batch kayıtları: 3 parti sıcaklık sapması not edilmiş : operatör değişiminde artış.", type: "capacity" }, { date: "2026-05-12", time: "13:20", text: "Atık geri kazanım ünitesi çıkış ölçümü uyumlu sınırda.", type: "observation" }, { date: "2026-05-05", time: "11:00", text: "ÇED uyarı yazısı ve yatırım planı çapraz kontrol edildi.", type: "inspection" }, { date: "2026-04-22", time: "14:30", text: "İhracat Irak fatura özetleri örneklendi.", type: "logistics" }, ], updates: [
    { date: "2026-05-20", time: "11:00", text: "Güvenlik protokolü ve batch kayıtları dosyaya eklendi." }, { date: "2026-05-12", time: "14:00", text: "Atıksu ölçüm raporu arşivlendi." }, { date: "2026-05-06", time: "09:30", text: "ÇED uyarısı ve yatırım planı bağlandı." }, { date: "2026-04-25", time: "16:15", text: "Saha ziyareti planı onaylandı." }, ], timeline: [
    { year: 2006, event: "Fason reçine üretim" }, { year: 2012, event: "Markalı endüstriyel reçine" }, { year: 2018, event: "Irak distribütör ağı" }, { year: 2024, event: "ÇED kapasite uyarısı" }, ], facilityNotes: [
    { zone: "Reaktör binası", note: "Ex-proof bölge" }, { zone: "Atıksu arıtma", note: "Kapasite uyarısı" }, { zone: "Dolum", note: "IBC ve varil" }, ], exportEvolution: [
    { year: 2015, market: "Irak", note: "İnşaat kimyasalları" }, { year: 2019, market: "Gürcistan", note: "Otomotiv reçine" }, { year: 2023, market: "Bulgaristan", note: "Küçük hacim OEM" }, ], inspectionLayers: [
    { layer: "Belge paketi", status: "partial", note: "ÇED dosyası tamam" }, { layer: "Saha doğrulama", status: "partial", note: "Reaktör ziyareti yapıldı" }, { layer: "Çevre uyumluluk", status: "partial", note: "Atıksu ölçümü kayıtlı" }, ], operationalSignals: [
    { label: "Aylık proses", value: "~420 ton" }, { label: "Batch sapma", value: "4 olay / 6 ay" }, { label: "İhracat payı", value: "Gelirin ~%35'i" }, { label: "Son saha", value: "20 Mayıs 2026" }, ],
});
