// Auto-generated from ISO 3166-1. Do not edit.
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "Afghanistan": "AF",
  "afghanistan": "AF",
  "Åland Islands": "AX",
  "åland islands": "AX",
  "Albania": "AL",
  "albania": "AL",
  "Algeria": "DZ",
  "algeria": "DZ",
  "American Samoa": "AS",
  "american samoa": "AS",
  "Andorra": "AD",
  "andorra": "AD",
  "Angola": "AO",
  "angola": "AO",
  "Anguilla": "AI",
  "anguilla": "AI",
  "Antarctica": "AQ",
  "antarctica": "AQ",
  "Antigua and Barbuda": "AG",
  "antigua and barbuda": "AG",
  "Argentina": "AR",
  "argentina": "AR",
  "Armenia": "AM",
  "armenia": "AM",
  "Aruba": "AW",
  "aruba": "AW",
  "Australia": "AU",
  "australia": "AU",
  "Austria": "AT",
  "austria": "AT",
  "Azerbaijan": "AZ",
  "azerbaijan": "AZ",
  "Bahamas": "BS",
  "bahamas": "BS",
  "Bahrain": "BH",
  "bahrain": "BH",
  "Bangladesh": "BD",
  "bangladesh": "BD",
  "Barbados": "BB",
  "barbados": "BB",
  "Belarus": "BY",
  "belarus": "BY",
  "Belgium": "BE",
  "belgium": "BE",
  "Belize": "BZ",
  "belize": "BZ",
  "Benin": "BJ",
  "benin": "BJ",
  "Bermuda": "BM",
  "bermuda": "BM",
  "Bhutan": "BT",
  "bhutan": "BT",
  "Bolivia, Plurinational State of": "BO",
  "bolivia, plurinational state of": "BO",
  "Bonaire, Sint Eustatius and Saba": "BQ",
  "bonaire, sint eustatius and saba": "BQ",
  "Bosnia and Herzegovina": "BA",
  "bosnia and herzegovina": "BA",
  "Botswana": "BW",
  "botswana": "BW",
  "Bouvet Island": "BV",
  "bouvet island": "BV",
  "Brazil": "BR",
  "brazil": "BR",
  "British Indian Ocean Territory": "IO",
  "british indian ocean territory": "IO",
  "Brunei Darussalam": "BN",
  "brunei darussalam": "BN",
  "Bulgaria": "BG",
  "bulgaria": "BG",
  "Burkina Faso": "BF",
  "burkina faso": "BF",
  "Burundi": "BI",
  "burundi": "BI",
  "Cabo Verde": "CV",
  "cabo verde": "CV",
  "Cambodia": "KH",
  "cambodia": "KH",
  "Cameroon": "CM",
  "cameroon": "CM",
  "Canada": "CA",
  "canada": "CA",
  "Cayman Islands": "KY",
  "cayman islands": "KY",
  "Central African Republic": "CF",
  "central african republic": "CF",
  "Chad": "TD",
  "chad": "TD",
  "Chile": "CL",
  "chile": "CL",
  "China": "CN",
  "china": "CN",
  "Christmas Island": "CX",
  "christmas island": "CX",
  "Cocos (Keeling) Islands": "CC",
  "cocos (keeling) islands": "CC",
  "Colombia": "CO",
  "colombia": "CO",
  "Comoros": "KM",
  "comoros": "KM",
  "Congo": "CG",
  "congo": "CG",
  "Congo, Democratic Republic of the": "CD",
  "congo, democratic republic of the": "CD",
  "Cook Islands": "CK",
  "cook islands": "CK",
  "Costa Rica": "CR",
  "costa rica": "CR",
  "Côte d'Ivoire": "CI",
  "côte d'ivoire": "CI",
  "Croatia": "HR",
  "croatia": "HR",
  "Cuba": "CU",
  "cuba": "CU",
  "Curaçao": "CW",
  "curaçao": "CW",
  "Cyprus": "CY",
  "cyprus": "CY",
  "Czechia": "CZ",
  "czechia": "CZ",
  "Denmark": "DK",
  "denmark": "DK",
  "Djibouti": "DJ",
  "djibouti": "DJ",
  "Dominica": "DM",
  "dominica": "DM",
  "Dominican Republic": "DO",
  "dominican republic": "DO",
  "Ecuador": "EC",
  "ecuador": "EC",
  "Egypt": "EG",
  "egypt": "EG",
  "El Salvador": "SV",
  "el salvador": "SV",
  "Equatorial Guinea": "GQ",
  "equatorial guinea": "GQ",
  "Eritrea": "ER",
  "eritrea": "ER",
  "Estonia": "EE",
  "estonia": "EE",
  "Eswatini": "SZ",
  "eswatini": "SZ",
  "Ethiopia": "ET",
  "ethiopia": "ET",
  "Falkland Islands (Malvinas)": "FK",
  "falkland islands (malvinas)": "FK",
  "Faroe Islands": "FO",
  "faroe islands": "FO",
  "Fiji": "FJ",
  "fiji": "FJ",
  "Finland": "FI",
  "finland": "FI",
  "France": "FR",
  "france": "FR",
  "French Guiana": "GF",
  "french guiana": "GF",
  "French Polynesia": "PF",
  "french polynesia": "PF",
  "French Southern Territories": "TF",
  "french southern territories": "TF",
  "Gabon": "GA",
  "gabon": "GA",
  "Gambia": "GM",
  "gambia": "GM",
  "Georgia": "GE",
  "georgia": "GE",
  "Germany": "DE",
  "germany": "DE",
  "Ghana": "GH",
  "ghana": "GH",
  "Gibraltar": "GI",
  "gibraltar": "GI",
  "Greece": "GR",
  "greece": "GR",
  "Greenland": "GL",
  "greenland": "GL",
  "Grenada": "GD",
  "grenada": "GD",
  "Guadeloupe": "GP",
  "guadeloupe": "GP",
  "Guam": "GU",
  "guam": "GU",
  "Guatemala": "GT",
  "guatemala": "GT",
  "Guernsey": "GG",
  "guernsey": "GG",
  "Guinea": "GN",
  "guinea": "GN",
  "Guinea-Bissau": "GW",
  "guinea-bissau": "GW",
  "Guyana": "GY",
  "guyana": "GY",
  "Haiti": "HT",
  "haiti": "HT",
  "Heard Island and McDonald Islands": "HM",
  "heard island and mcdonald islands": "HM",
  "Holy See": "VA",
  "holy see": "VA",
  "Honduras": "HN",
  "honduras": "HN",
  "Hong Kong": "HK",
  "hong kong": "HK",
  "Hungary": "HU",
  "hungary": "HU",
  "Iceland": "IS",
  "iceland": "IS",
  "India": "IN",
  "india": "IN",
  "Indonesia": "ID",
  "indonesia": "ID",
  "Iran, Islamic Republic of": "IR",
  "iran, islamic republic of": "IR",
  "Iraq": "IQ",
  "iraq": "IQ",
  "Ireland": "IE",
  "ireland": "IE",
  "Isle of Man": "IM",
  "isle of man": "IM",
  "Israel": "IL",
  "israel": "IL",
  "Italy": "IT",
  "italy": "IT",
  "Jamaica": "JM",
  "jamaica": "JM",
  "Japan": "JP",
  "japan": "JP",
  "Jersey": "JE",
  "jersey": "JE",
  "Jordan": "JO",
  "jordan": "JO",
  "Kazakhstan": "KZ",
  "kazakhstan": "KZ",
  "Kenya": "KE",
  "kenya": "KE",
  "Kiribati": "KI",
  "kiribati": "KI",
  "Korea, Democratic People's Republic of": "KP",
  "korea, democratic people's republic of": "KP",
  "Korea, Republic of": "KR",
  "korea, republic of": "KR",
  "Kuwait": "KW",
  "kuwait": "KW",
  "Kyrgyzstan": "KG",
  "kyrgyzstan": "KG",
  "Lao People's Democratic Republic": "LA",
  "lao people's democratic republic": "LA",
  "Latvia": "LV",
  "latvia": "LV",
  "Lebanon": "LB",
  "lebanon": "LB",
  "Lesotho": "LS",
  "lesotho": "LS",
  "Liberia": "LR",
  "liberia": "LR",
  "Libya": "LY",
  "libya": "LY",
  "Liechtenstein": "LI",
  "liechtenstein": "LI",
  "Lithuania": "LT",
  "lithuania": "LT",
  "Luxembourg": "LU",
  "luxembourg": "LU",
  "Macao": "MO",
  "macao": "MO",
  "Madagascar": "MG",
  "madagascar": "MG",
  "Malawi": "MW",
  "malawi": "MW",
  "Malaysia": "MY",
  "malaysia": "MY",
  "Maldives": "MV",
  "maldives": "MV",
  "Mali": "ML",
  "mali": "ML",
  "Malta": "MT",
  "malta": "MT",
  "Marshall Islands": "MH",
  "marshall islands": "MH",
  "Martinique": "MQ",
  "martinique": "MQ",
  "Mauritania": "MR",
  "mauritania": "MR",
  "Mauritius": "MU",
  "mauritius": "MU",
  "Mayotte": "YT",
  "mayotte": "YT",
  "Mexico": "MX",
  "mexico": "MX",
  "Micronesia, Federated States of": "FM",
  "micronesia, federated states of": "FM",
  "Moldova, Republic of": "MD",
  "moldova, republic of": "MD",
  "Monaco": "MC",
  "monaco": "MC",
  "Mongolia": "MN",
  "mongolia": "MN",
  "Montenegro": "ME",
  "montenegro": "ME",
  "Montserrat": "MS",
  "montserrat": "MS",
  "Morocco": "MA",
  "morocco": "MA",
  "Mozambique": "MZ",
  "mozambique": "MZ",
  "Myanmar": "MM",
  "myanmar": "MM",
  "Namibia": "NA",
  "namibia": "NA",
  "Nauru": "NR",
  "nauru": "NR",
  "Nepal": "NP",
  "nepal": "NP",
  "Netherlands, Kingdom of the": "NL",
  "netherlands, kingdom of the": "NL",
  "New Caledonia": "NC",
  "new caledonia": "NC",
  "New Zealand": "NZ",
  "new zealand": "NZ",
  "Nicaragua": "NI",
  "nicaragua": "NI",
  "Niger": "NE",
  "niger": "NE",
  "Nigeria": "NG",
  "nigeria": "NG",
  "Niue": "NU",
  "niue": "NU",
  "Norfolk Island": "NF",
  "norfolk island": "NF",
  "North Macedonia": "MK",
  "north macedonia": "MK",
  "Northern Mariana Islands": "MP",
  "northern mariana islands": "MP",
  "Norway": "NO",
  "norway": "NO",
  "Oman": "OM",
  "oman": "OM",
  "Pakistan": "PK",
  "pakistan": "PK",
  "Palau": "PW",
  "palau": "PW",
  "Palestine, State of": "PS",
  "palestine, state of": "PS",
  "Panama": "PA",
  "panama": "PA",
  "Papua New Guinea": "PG",
  "papua new guinea": "PG",
  "Paraguay": "PY",
  "paraguay": "PY",
  "Peru": "PE",
  "peru": "PE",
  "Philippines": "PH",
  "philippines": "PH",
  "Pitcairn": "PN",
  "pitcairn": "PN",
  "Poland": "PL",
  "poland": "PL",
  "Portugal": "PT",
  "portugal": "PT",
  "Puerto Rico": "PR",
  "puerto rico": "PR",
  "Qatar": "QA",
  "qatar": "QA",
  "Réunion": "RE",
  "réunion": "RE",
  "Romania": "RO",
  "romania": "RO",
  "Russian Federation": "RU",
  "russian federation": "RU",
  "Rwanda": "RW",
  "rwanda": "RW",
  "Saint Barthélemy": "BL",
  "saint barthélemy": "BL",
  "Saint Helena, Ascension and Tristan da Cunha": "SH",
  "saint helena, ascension and tristan da cunha": "SH",
  "Saint Kitts and Nevis": "KN",
  "saint kitts and nevis": "KN",
  "Saint Lucia": "LC",
  "saint lucia": "LC",
  "Saint Martin (French part)": "MF",
  "saint martin (french part)": "MF",
  "Saint Pierre and Miquelon": "PM",
  "saint pierre and miquelon": "PM",
  "Saint Vincent and the Grenadines": "VC",
  "saint vincent and the grenadines": "VC",
  "Samoa": "WS",
  "samoa": "WS",
  "San Marino": "SM",
  "san marino": "SM",
  "Sao Tome and Principe": "ST",
  "sao tome and principe": "ST",
  "Saudi Arabia": "SA",
  "saudi arabia": "SA",
  "Senegal": "SN",
  "senegal": "SN",
  "Serbia": "RS",
  "serbia": "RS",
  "Seychelles": "SC",
  "seychelles": "SC",
  "Sierra Leone": "SL",
  "sierra leone": "SL",
  "Singapore": "SG",
  "singapore": "SG",
  "Sint Maarten (Dutch part)": "SX",
  "sint maarten (dutch part)": "SX",
  "Slovakia": "SK",
  "slovakia": "SK",
  "Slovenia": "SI",
  "slovenia": "SI",
  "Solomon Islands": "SB",
  "solomon islands": "SB",
  "Somalia": "SO",
  "somalia": "SO",
  "South Africa": "ZA",
  "south africa": "ZA",
  "South Georgia and the South Sandwich Islands": "GS",
  "south georgia and the south sandwich islands": "GS",
  "South Sudan": "SS",
  "south sudan": "SS",
  "Spain": "ES",
  "spain": "ES",
  "Sri Lanka": "LK",
  "sri lanka": "LK",
  "Sudan": "SD",
  "sudan": "SD",
  "Suriname": "SR",
  "suriname": "SR",
  "Svalbard and Jan Mayen": "SJ",
  "svalbard and jan mayen": "SJ",
  "Sweden": "SE",
  "sweden": "SE",
  "Switzerland": "CH",
  "switzerland": "CH",
  "Syrian Arab Republic": "SY",
  "syrian arab republic": "SY",
  "Taiwan, Province of China": "TW",
  "taiwan, province of china": "TW",
  "Tajikistan": "TJ",
  "tajikistan": "TJ",
  "Tanzania, United Republic of": "TZ",
  "tanzania, united republic of": "TZ",
  "Thailand": "TH",
  "thailand": "TH",
  "Timor-Leste": "TL",
  "timor-leste": "TL",
  "Togo": "TG",
  "togo": "TG",
  "Tokelau": "TK",
  "tokelau": "TK",
  "Tonga": "TO",
  "tonga": "TO",
  "Trinidad and Tobago": "TT",
  "trinidad and tobago": "TT",
  "Tunisia": "TN",
  "tunisia": "TN",
  "Türkiye": "TR",
  "türkiye": "TR",
  "Turkmenistan": "TM",
  "turkmenistan": "TM",
  "Turks and Caicos Islands": "TC",
  "turks and caicos islands": "TC",
  "Tuvalu": "TV",
  "tuvalu": "TV",
  "Uganda": "UG",
  "uganda": "UG",
  "Ukraine": "UA",
  "ukraine": "UA",
  "United Arab Emirates": "AE",
  "united arab emirates": "AE",
  "United Kingdom of Great Britain and Northern Ireland": "GB",
  "united kingdom of great britain and northern ireland": "GB",
  "United States of America": "US",
  "united states of america": "US",
  "United States Minor Outlying Islands": "UM",
  "united states minor outlying islands": "UM",
  "Uruguay": "UY",
  "uruguay": "UY",
  "Uzbekistan": "UZ",
  "uzbekistan": "UZ",
  "Vanuatu": "VU",
  "vanuatu": "VU",
  "Venezuela, Bolivarian Republic of": "VE",
  "venezuela, bolivarian republic of": "VE",
  "Viet Nam": "VN",
  "viet nam": "VN",
  "Virgin Islands (British)": "VG",
  "virgin islands (british)": "VG",
  "Virgin Islands (U.S.)": "VI",
  "virgin islands (u.s.)": "VI",
  "Wallis and Futuna": "WF",
  "wallis and futuna": "WF",
  "Western Sahara": "EH",
  "western sahara": "EH",
  "Yemen": "YE",
  "yemen": "YE",
  "Zambia": "ZM",
  "zambia": "ZM",
  "Zimbabwe": "ZW",
  "zimbabwe": "ZW",
  "Vietnam": "VN",
  "vietnam": "VN",
  "Russia": "RU",
  "russia": "RU",
  "Czech Republic": "CZ",
  "czech republic": "CZ",
  "Turkey": "TR",
  "turkey": "TR",
  "UK": "GB",
  "uk": "GB",
  "United Kingdom": "GB",
  "united kingdom": "GB",
  "USA": "US",
  "usa": "US",
  "United States": "US",
  "united states": "US",
  "South Korea": "KR",
  "south korea": "KR",
  "Netherlands": "NL",
  "netherlands": "NL",
  "Tanzania": "TZ",
  "tanzania": "TZ",
  "Bolivia": "BO",
  "bolivia": "BO",
  "Venezuela": "VE",
  "venezuela": "VE",
  "Iran": "IR",
  "iran": "IR",
  "Laos": "LA",
  "laos": "LA",
  "North Korea": "KP",
  "north korea": "KP",
  "Palestine": "PS",
  "palestine": "PS",
  "Syria": "SY",
  "syria": "SY",
  "Macedonia": "MK",
  "macedonia": "MK",
  "Moldova": "MD",
  "moldova": "MD",
  "Ivory Coast": "CI",
  "ivory coast": "CI",
  "Cape Verde": "CV",
  "cape verde": "CV",
  "Brunei": "BN",
  "brunei": "BN",
  "East Timor": "TL",
  "east timor": "TL",
  "Swaziland": "SZ",
  "swaziland": "SZ",
  "Taiwan": "TW",
  "taiwan": "TW",
  "Macau": "MO",
  "macau": "MO",
  "Any": "CN",
  "any": "CN"
};

export const CODE_TO_DISPLAY: Record<string, string> = {
  "AF": "Afghanistan",
  "AX": "Åland Islands",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia, Plurinational State of",
  "BQ": "Bonaire, Sint Eustatius and Saba",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cabo Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo, Democratic Republic of the",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Côte d'Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "SZ": "Eswatini",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island and McDonald Islands",
  "VA": "Holy See",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran, Islamic Republic of",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States of",
  "MD": "Moldova, Republic of",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands, Kingdom of the",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MK": "North Macedonia",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestine, State of",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin (French part)",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten (Dutch part)",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and the South Sandwich Islands",
  "SS": "South Sudan",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan, Province of China",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Türkiye",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom of Great Britain and Northern Ireland",
  "US": "United States of America",
  "UM": "United States Minor Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela, Bolivarian Republic of",
  "VN": "Viet Nam",
  "VG": "Virgin Islands (British)",
  "VI": "Virgin Islands (U.S.)",
  "WF": "Wallis and Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};
